name: 01. Basic Workflow
on:
  push:
    branches:
      - main
jobs:
  matrix-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  reusable-workflow-1:
    uses: ./.github/workflows/sample.yml
    with:
      some-input: some-value
  
  reusable-workflow-2:
    uses: ./.github/workflows/sample.yml
    with:
      some-input: some-value

  custom-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom JavaScript action
        uses: ./.github/actions/custom-js-action
        with:
          name: 'GitHub Actions Workshop'